services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
    ports:
      - "0.0.0.0:5001:80"
  backend:
    container_name: backend
    image: backend
    build:
      context: backend
    stop_grace_period: 1s
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - backend-network
  db:
    image: "mongo"
    container_name: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend-network


networks:
  backend-network:
    # Specify driver options
    driver: bridge
    